version: '3.8'

services:
  vaccine:
    image: pydemic/vaccine_simulation_notebooks:production
    environment:
      LANG: pt_BR.UTF-8
      # STREAMLIT_BROWSER_SERVER_ADDRESS: some_domain.org
      # STREAMLIT_BROWSER_SERVER_PORT: '80'
      STREAMLIT_SERVER_ADDRESS: 0.0.0.0
      STREAMLIT_SERVER_ENABLE_CORS: 'false'
      STREAMLIT_SERVER_PORT: '8551'
    ports:
      - 8551:8551
